config/routes.rb
Rails.application.routes.draw do
  root to: 'profile#index'
  get '/profile', to: 'profile#index'
  resources :profile
  get '/parks', to: 'parks#index'
  get '/checkin', to: 'checkin#index'
  get '/wallet', to: 'wallets#index'
  get '/advocacy', to: 'advocacy#index'
  get '/dsreturn', to: 'advocacy#index'
  post '/profile/:id', to: 'profile#update'
  post '/checkin', to: 'checkin#new'
  resources :advocacy
end

app/models/advocacy.rb
class Advocacy < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkin.rb
class Checkin < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :advocacies
  has_many :users, through: :advocacies
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :advocacies
  has_many :issues, through: :advocacies
  has_many :checkins
end

app/controllers/advocacy_controller.rb
class AdvocacyController < ApplicationController
  def index

    @thank = "false"
    if session[:supporting_issue].present?
      @thank = "true"
      @supporting_issue = session.delete(:supporting_issue)


      Advocacy.create(user_id: session[:user_id], issue_id: session[:issue_id])
      result = `python3 ./lib/scripts/get_reps.py --zip "50014"`
      # Get senator details
      @sent_to = "Senator #{result.split("\n").first.split(",")[-3].split("'").last} at #{result.split("\n").first.split(",").last.split("'")[1]}"
    end
   puts "#{@thank}"

    @issues = Issue.all
    @supported = User.find(session[:user_id]).advocacies.map(&:issue_id)
  end

  def edit
    # TODO : CALL script and get docusign redirect path. Check what to send.
    session[:issue_id] = params[:id]
    session[:supporting_issue] = Issue.find(params[:id]).title

    result = `python3 ./lib/scripts/ICareActivity.py --issueId="issue#{params[:id]}" --hostUrl="http://08eca4bc.ngrok.io"`
    url= result.split("\n")[-1]
    # Advocacy.create(user_id: session[:user_id], issue_id: params[:id])
    redirect_to url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user
  skip_before_action :verify_authenticity_token

  def set_user
    return if session[:user_id].present?
    user = User.last
    session[:user_id] = user.id
    %I(username first_name last_name email zip).each do |attr|
      session[attr] = user.send(attr)
    end
  end
end

app/controllers/checkin_controller.rb
class CheckinController < ApplicationController
  def index
    @checkins = User.find(session[:user_id]).checkins.includes(:location).order('created_at DESC')
  end

  def new
    begin
    result = `python3 ./lib/scripts/checkin.py --lat 38.733082 --long -109.592514`
    location_name = result.split('\n').first
    rescue StandardError
      location_name = "Arches National Park"
    end
    location = Location.find_by_name(location_name)
    location = Location.create(name: location_name,lattitude: "38.733082", longitude: "-109.592514", state: "CA" ) unless location.present?
    name = "#{location.name.split(" ").first.downcase}.#{params['file'].path.split('.').last}"
    FileUtils.mv(params['file'].path,"#{Rails.root.to_s}/app/assets/images/#{name}")
    Checkin.create(user_id: session[:user_id],lattitude: "38.733082", longitude: "-109.592514", location: location, image: name )
    render json: {
      suceess: true
    }
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    @parks = Location.all
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = User.last
  end

  def update
    User.find(params[:id]).update(user_params.to_h)
    redirect_to profile_path
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :zip, :email, :phone_number, :username)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
end

app/helpers/advocacy_helper.rb
module AdvocacyHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkin_helper.rb
module CheckinHelper
end

app/helpers/parks_helper.rb
module ParksHelper
  IMAGES = %w(artic_refuge.gif background.jpg central_cali.jpg chaco_canyon.jpeg channel.jpg
      joshua.jpg malibu.jpg mojave.jpg topanga.jpg whiskeytown.jpg yosemite.jpg)
  def get_random_image
    IMAGES[Random.new.rand(0..10)]
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/advocacy/index.html.erb
<div class="row advocacy">
    <% @issues.each do |issue|%>
      <div class="col-sm">
      <div class="card" >

        <img class="card-img-top" src="/assets/<%= issue.attachment_link %>" alt="Card image cap">
        <div class="card-body">
          <% if @supported.include?(issue.id) %>
            <div class="ribbon ribbon-top-right"><span>Supporting!</span></div>
          <% end %>
          <!-- Title -->
          <h4 class="card-title"><%= issue.title %></h4>
          <hr>
          <!-- Text -->
          <p class="card-text"><%= issue.summary %></p>
          <div class="container">
            <div class="row">
              <div class="col">
                <div class="offer-points-text">
                  +<%= issue.supported %> Signed
                </div>
              </div>
              <div class="col">
                <a href="#!" class="black-text d-flex justify-content-end" data-toggle="modal" data-target="#portfolioModal<%= issue.id %>">Learn More</a>
              </div>
            </div>
          </div>
          <!-- Link -->
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% @issues.each do |issue|%>
    <div class="portfolio-modal modal fade" id="portfolioModal<%= issue.id %>" tabindex="-1" role="dialog" aria-labelledby="portfolioModal<%= issue.id %>Label" aria-hidden="true">
      <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
            </button>

          <div class="modal-body text-center">
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-lg-12">
                  <!-- Portfolio Modal - Title -->
                  <h2 class="portfolio-modal-title text-secondary text-uppercase mb-0"><%= issue.title %></h2>
                  <!-- Icon Divider -->
                  <div class="divider-custom">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon">
                      <i class="fas fa-star"></i>
                    </div>
                    <div class="divider-custom-line"></div>
                  </div>
                  <!-- Portfolio Modal - Image -->
                  <img class="img-fluid rounded mb-5" src="/assets/<%= issue.attachment_link %>" alt="">
                  <!-- Portfolio Modal - Text -->
                  <p class="mb-lg-5"><%= issue.description.html_safe %></p>
                  <% if @supported.include?(issue.id) %>
                      <a class="btn btn-success" id="payContainer" href="https://secure.wilderness.org/page/42457/donate/1?_ga=2.201703633.1902207102.1560093327-1070288338.1560093327" role="button">Donate !</a>
                  <% else %>
                    <a class="btn btn-success" href=<%= edit_advocacy_path(issue.id)%> role="button">I Care !</a>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <input type="hidden" id="thank_you" value="<%= @thank %>">

  <div class="modal fade" id="thankyoumodal" tabindex="-1" role="dialog" aria-labelledby="thankyoumodalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: 10px">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>

        <div class="modal-body">
          <div class="jumbotron jumbotron-fluid">
              <div class="container">
                <p class="lead text-center">Thank you for supporting <b><%= @supporting_issue %>.</b></p>
                <hr>
                <p class="lead text-center">  A personal e-mail has been sent to <b><%= @sent_to %></b> on your behalf.</p>
                <hr>
                <p class="lead text-center">  You have made a valuable contribution to the cause of preserving nature !</p>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/checkin/index.html.erb
<button type="button" id="checkin_now" data-toggle="modal" data-target="#checkin_form" class="btn btn-secondary btn-lg btn-block" style="margin-bottom: 30px; border-radius: 20px">Check In Now</button>
<% @checkins.each_slice(3) do |checkins| %>
  <div class="card-deck" style="margin-bottom: 20px">
    <% if checkins[0].present? %>
      <div class="card">
        <img src="/assets/<%= checkins[0].image %>" class="card-img-top rounded" style="margin-bottom: 20px">
        <div class="card-body">
          <h5 class="card-title"><%= checkins[0].location.name %>
            <a href="#!" id="btn-share" data-toggle="modal" data-target="#share_modal"><i class="fas fa-share-alt" style="float: right"></i></a>
          </h5>
          <hr>
          <p class="card-text">Visited on - <%= checkins[0].created_at.strftime("%B %d, %Y") %></p>
        </div>
      </div>
    <% end %>
    <% if checkins[1].present? %>
      <div class="card">
        <img src="/assets/<%= checkins[1].image %>" class="card-img-top rounded" style="margin-bottom: 20px">
        <div class="card-body">
          <h5 class="card-title"><%= checkins[1].location.name %>
            <a href="#!" id="btn-share" data-toggle="modal" data-target="#share_modal"><i class="fas fa-share-alt" style="float: right"></i></a>
          </h5>
          <hr>
          <p class="card-text">Visited on - <%= checkins[1].created_at.strftime("%B %d, %Y") %></p>
        </div>
      </div>
    <% end %>
    <% if checkins[2].present? %>
      <div class="card">
        <img src="/assets/<%= checkins[2].image %>" class="card-img-top rounded" style="margin-bottom: 20px">
        <div class="card-body">
          <h5 class="card-title"><%= checkins[2].location.name %>
            <a href="#!" id="btn-share" data-toggle="modal" data-target="#share_modal"><i class="fas fa-share-alt" style="float: right"></i></a>
          </h5>
          <hr>
          <p class="card-text">Visited on - <%= checkins[2].created_at.strftime("%B %d, %Y") %></p>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

<div class="modal fade" id="share_modal" tabindex="-1" role="dialog" aria-labelledby="share_modallabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: 10px">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
      </button>

      <div class="modal-body">
          <div class="container">
            <div class="row">
              <div class="col">
                <a class="btn btn-block btn-social btn-facebook">
                  <i class="fab fa-facebook-square"></i> Share on Facebook
                </a>
                <a class="btn btn-block btn-social btn-flickr">
                  <i class="fab fa-flickr"></i> Share on Flickr
                </a>
                <a class="btn btn-block btn-social btn-instagram">
                  <i class="fab fa-instagram"></i> Share on Instagram
                </a>
                <a class="btn btn-block btn-social btn-twitter">
                  <i class="fab fa-twitter"></i> Share on Twitter
                </a>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="checkin_form" tabindex="-1" role="dialog" aria-labelledby="checkin_form_label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Check In Now !</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <form id="checkin-image-form">
            <div class="form-group">
              <div class="custom-file">
                <input id="checkin-image-input" name="csv_input" type="file" class="custom-file-input">
                <label for="checkin-image-input" id="checkin-image-label" class="custom-file-label text-truncate">Choose file...</label>
              </div>
            </div>
          </form>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button class="btn btn-primary" id="checkin-image-submit">Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<nav id="sidebar" class="sidebar-wrapper">
  <div class="sidebar-content">
    <!-- sidebar-brand  -->
    <div class="sidebar-item sidebar-brand">
      <a href="/"><img src="/assets/gowild-logo.png" style="height: 40px"></a>
    </div>
    <!-- sidebar-header  -->
    <div class="sidebar-item sidebar-header d-flex flex-nowrap">
      <div class="user-pic">
        <img class="img-responsive img-rounded" src="/assets/wick.jpg" alt="User picture" style="border-radius: 15px">
      </div>
      <div class="user-info">
                        <span class="user-name"><%= session[:first_name] %>
                            <strong><%= session[:last_name] %></strong>
                        </span>
        <span class="user-role"><%= session[:username] %></span>
      </div>
    </div>
    <!-- sidebar-menu  -->
    <div class=" sidebar-item sidebar-menu">
      <ul>
        <li class="sidebar-submenu <%= 'active' if current_page?(profile_path) || current_page?(root_path)%>">
          <a href="/profile">
            <i class="fas fa-user-alt"></i>
            <span class="menu-text">Profile</span>
          </a>
        </li>
        <li class="sidebar-submenu <%= 'active' if current_page?(wallet_path)%>">
          <a href="/wallet">
            <i class="fas fa-wallet"></i>
            <span class="menu-text">Wallet</span>
          </a>
        </li>
        <li class="sidebar-submenu <%= 'active' if current_page?(checkin_path)%>">
          <a href="/checkin">
            <i class="fas fa-map-pin"></i>
            <span class="menu-text">Check-ins</span>
          </a>
        </li>
        <li class="sidebar-submenu <%= 'active' if current_page?(advocacy_path)%>">
          <a href="/advocacy">
            <i class="fas fa-vote-yea badge-sonar"></i>
            <span class="menu-text">
              Advocacy
              <span class="badge badge-pill badge-danger">New !</span>
            </span>
          </a>
        </li>
        <li class="sidebar-submenu  <%= 'active' if current_page?(parks_path)%>">
          <a href="/parks">
            <i class="fas fa-tree"></i>
            <span class="menu-text">Parks</span>
          </a>
        </li>
      </ul>
    </div>
    <!-- sidebar-menu  -->
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Go Wild" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Docusign" %>">
<!--  <script src="https://github.com/pipwerks/PDFObject/blob/master/pdfobject.min.js"></script>-->
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="https://kit.fontawesome.com/ed1beaaff6.js"></script>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="page-wrapper default-theme sidebar-bg bg1 toggled" >
      <%= render 'layouts/navigation' %>        <!-- page-content  -->
      <main class="page-content pt-2">
        <a id="toggle-sidebar" class="btn btn-secondary" href="#">
          <i class="fas fa-bars"></i>
        </a>
        <div id="overlay" class="overlay"></div>
        <div class="container-fluid p-5">

          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/parks/index.html.erb
<!--<img class="img-responsive" src="/assets/coming_soon">-->
<div class="container-fluid">
  <% @parks.each do |park|%>
    <div class="col-lg-6 mb-4">
      <div class="card text-white shadow" style="background-size: 260px 80px;background-image: url('/assets/<%= get_random_image %>')">
        <div class="card-body">
          <%= park.name %>
          <div class="text-white-50 small"><%= park.state %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/visitors/index.html.erb
<h1>Visitors</h1>

app/views/wallets/index.html.erb
<div class="container">
  <img class="img-responsive pass-image" src="/assets/pass_front.png" style="margin-bottom: 20px">
  <img class="img-responsive pass-image" src="/assets/pass_back.jpg" style="margin-top: 20px">
</div>